### ISSUE TITLE
Picture puzzle

### ISSUE THREAD

**Issue by voelkerb** [ubilab-ws21/esclab#14]
If I remember correctly the following issues occurred during the last run:

- [x] time too long even for doing it alone
- [x] fix random reset of ESPs
- [x] hold down white button (from robot puzzle last year) at the same time so that you cannot run
  - [x] test if button sends MQTT msg if pressed/released, if not, change code so that it does and that the old puzzle still works
- [x] indicate end of game via radio or text to speech and lights

**Comment by JannikMaeder** [comment]
We adjusted the time per picture and per sequence and will test it next week in the escape room. We were also able to solve the random resets of the ESPs by including a reconnect function. 
Regarding the button, which needs to be pressed to complete the puzzle: We decided to use one of the remaining arcade buttons we ordered. The button is now connected to the timer, which now sends MQTT messages when the button is pressed. The code on the Raspberry then checks if the button is pressed at all times. Otherwise the puzzle is restarted. Next week we will drill a hole next to the display, so that the button can be placed there.
We also worked on how to end our puzzle. When the puzzle is solved a progress bar gets shown on the display and we will notify the player over the TTS system. Maybe we can also think about turning on the lights in the room, when the puzzle is solved. 

This leaves us with the following things to do:

* [x]  time too long even for doing it alone
* [x]  fix random reset of ESPs
* [x]  hold down white button (from robot puzzle last year) at the same time so that you cannot run
  * [x]  test if button sends MQTT msg if pressed/released, if not, change code so that it does and that the old puzzle still works
* [x]  indicate end of game (via radio or text to speech and) lights
* [x]  change all outside MQTT-communication to the JSON-format
* [x]  talk to the preceding puzzle about what kind of message they will send us.

**Comment by voelkerb** [comment]
Nice work! 
Regarding the message from the puzzle before: You will get an mqtt message from the operator; the messages for tts and lights can be sent from the operator as well but we need to think of which exactly and then @sboettcher can include it in the game flow ;)

**Comment by sboettcher** [comment]
Yes, you will automatically get a trigger:on message ([in the specified json format](https://github.com/ubilab-ws21/operator#communication-format)) once your puzzle is coming next in the game flow. If you need any other info from the previous puzzle you need to work that out with that group though.

**Comment by voelkerb** [comment]
@Group: Have you tested everything - and it is working including MQTT activate, and solved?

**Comment by voelkerb** [comment]
If so, please close the issue

**Comment by JannikMaeder** [comment]
Yes, everything is working! So this issue can be closed (Sorry, I can‘t figure out how to close issues)

**Comment by voelkerb** [comment]
Perfect!
